import React, { useState } from 'react';
import { generateCompanyVision } from '../services/geminiService';
import { VisionResponse } from '../types';

export const AiVisionSection: React.FC = () => {
  const [vision, setVision] = useState<VisionResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [theme, setTheme] = useState('Cyberpunk Aesthetics');

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const data = await generateCompanyVision(theme);
      setVision(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section 
      id="vision" 
      className="h-screen w-full snap-start relative flex items-center justify-center bg-black overflow-hidden"
    >
       {/* Dynamic Background Image based on state slightly */}
      <div className="absolute inset-0 opacity-40">
        <img 
          src="https://picsum.photos/seed/abstract/1920/1080" 
          alt="Abstract" 
          className="w-full h-full object-cover grayscale contrast-125"
        />
      </div>
      
      <div className="absolute inset-0 bg-gradient-to-r from-black via-black/80 to-transparent"></div>

      <div className="relative z-10 container mx-auto px-4 flex flex-col md:flex-row items-center gap-12">
        <div className="md:w-1/2">
          <h2 className="text-4xl md:text-6xl font-serif text-white mb-6">
            AI-Driven <br/>
            <span className="text-cyan-400">Creation</span>
          </h2>
          <p className="text-gray-400 mb-8 font-sans max-w-md">
            Harnessing the power of Gemini 2.5 Flash to sculpt the narrative of tomorrow.
            Define a theme, and let intelligence craft your manifesto.
          </p>

          <div className="flex flex-col gap-4 max-w-sm">
            <select 
              value={theme}
              onChange={(e) => setTheme(e.target.value)}
              className="bg-zinc-800 border border-zinc-700 text-white p-3 rounded-lg focus:outline-none focus:border-cyan-500 font-sans"
            >
              <option>Cyberpunk Aesthetics</option>
              <option>Minimalist Zen</option>
              <option>Sustainable Future</option>
              <option>Space Exploration</option>
            </select>
            
            <button
              onClick={handleGenerate}
              disabled={loading}
              className={`
                px-8 py-4 bg-cyan-600 hover:bg-cyan-500 text-white font-bold rounded-lg transition-all 
                flex items-center justify-center gap-2 shadow-lg shadow-cyan-500/30
                ${loading ? 'opacity-50 cursor-not-allowed' : ''}
              `}
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-white rounded-full animate-bounce"></span>
                  <span className="w-2 h-2 bg-white rounded-full animate-bounce delay-75"></span>
                  <span className="w-2 h-2 bg-white rounded-full animate-bounce delay-150"></span>
                </span>
              ) : (
                'Generate Vision'
              )}
            </button>
          </div>
        </div>

        <div className="md:w-1/2 w-full">
          <div className="bg-glassDark backdrop-blur-md border border-white/10 p-8 rounded-2xl min-h-[300px] flex flex-col justify-center relative overflow-hidden">
            {!vision && !loading && (
              <div className="text-center text-gray-500 font-sans">
                <p>Waiting for neural input...</p>
              </div>
            )}
            
            {vision && (
              <div className="animate-in fade-in duration-700 slide-in-from-bottom-4">
                <div className="mb-6 flex gap-2 flex-wrap">
                  {vision.keywords.map((k, i) => (
                    <span key={i} className="px-3 py-1 bg-white/10 rounded-full text-xs font-mono text-cyan-300 border border-cyan-500/30">
                      #{k}
                    </span>
                  ))}
                </div>
                <h3 className="text-2xl md:text-3xl font-serif text-white leading-relaxed italic">
                  "{vision.statement}"
                </h3>
                <div className="mt-6 flex items-center gap-2 text-xs text-gray-500 font-mono">
                  <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                  GENERATED BY GEMINI 2.5
                </div>
              </div>
            )}

            {/* Decorative Grid */}
            <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:20px_20px] pointer-events-none -z-10"></div>
          </div>
        </div>
      </div>
    </section>
  );
};
